from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, EmailStr

"""
This module defines the Pydantic models (schemas) for the API.

These schemas are used to validate and structure the data for users and the quizzes. 
It ennsures that the incoming and the outgoing data meet the expected format and types.

Classes:
- UserBase, UserCreate, UserOut: Schemas for user-data.
- QuizBase, QuizCreate, QuizOut: Schemas for quiz-data.
- QuestionBase, QuestionCreate, QuestionOut: Schemas for question-data.
"""



# ----- USERS ------
# Represents people that are using the system (teachers, hosts and players)

class UserBase(BaseModel):
    # The "core" fields that is shared between input and output
    username: str
    email: EmailStr       # Creates a valid type for emails that looks like: (something@example.com). Other types will be rejected (FastAPI automatically returns a 422 Validation Error)
    role: str             # Admin/teacher/player


class UserCreate(UserBase):
    # Used when creating a user (POST /users)
    password: str         # plain password from client


class UserOut(UserBase):
    # Used when returning user data to the client
    id: int                 # The id that's generated by the database
    created_at: datetime    # Timestamp from database

    model_config = ConfigDict(from_attributes=True) # Lets FastAPI read data from dictionaries / ORM-like objects


# ----- QUIZZES -----
# A quiz is created by a host or a teacher.
# One quiz have many questions and many live sessions.

class QuizBase(BaseModel):
    # The quiz that is shared between the users
    title: str
    description: Optional[str] = None # Optional means "this field can be missing or None (Nullable in database)"
    visibility: Optional[str] = None  # 'public' or 'private'


class QuizCreate(QuizBase):
    # Used when creating a quiz (POST /quizzes)
    creator_id: int


class QuizOut(QuizBase):
    # Used when returning quizzes to clients
    id: int
    creator_id: int
    created_at: datetime
    updated_at: Optional[datetime]

    model_config = ConfigDict(from_attributes=True)


# ----- QUESTIONS -----
# The questions belongs to a quiz, which have many questions.

class QuestionBase(BaseModel):
    # The questions that's in the quiz
    question_text: str          # The question that's shown to players
    question_type: str          # Whenever a question has multiple choices (True/False, multiple answers)
    time_limit_seconds: Optional[int] = None
    points: Optional[int] = None
    sort_order: Optional[int] = None # The order in the quiz


class QuestionCreate(QuestionBase):
    # Used when creating a question
    quiz_id: int


class QuestionOut(QuestionBase):
    # Used when returning questions from the API
    id: int
    quiz_id: int

    model_config = ConfigDict(from_attributes=True)
